services:
  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bruss
      MONGO_INITDB_ROOT_PASSWORD: ${BRUSS_DB_PASSWORD:?}

  api:
    image: topongo/bruss
    build: .
    environment:
      RUST_LOG: info
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
      ROCKET_LOG_LEVEL: debug
      ROCKET_DATABASES: "{bruss={url=\"mongodb://bruss:${BRUSS_DB_PASSWORD:?}@${BRUSS_DB_HOST:-db}\"}}"
    volumes:
      - ./bruss.toml:/app/bruss.toml
    ports:
      - "80:8000"
    command: bruss_api

  router:
    image: topongo/bruss
    build: .
    environment:
      RUST_LOG: bruss_fetch=info,bruss_route=info
    volumes:
      - ./bruss.toml:/app/bruss.toml

volumes:
  mongodb_data:
